### ISSUE TITLE
Nodejs Express and jspos

### ISSUE THREAD

**Issue by mehrshadghaderian** [sitb-software/jsPOS#17]
please help me

i use jpos  in .net project in enterprise Project .  but now  when i  see   npm-jspos i realy happy .

i use  from your example 
but becase of i dont have typescript file in express frame work  i change  code but i have error in 'msg.pack()'

Error: null field 11 packager
    at MyPackager.pack (D:\SwitchJS\citydiSwicthNodeV1\node_modules\jspos\lib\ISOBasePackager.js:144:31)
    at ISOMsg.pack (D:\SwitchJS\citydiSwicthNodeV1\node_modules\jspos\lib\ISOMsg.js:180:34)
    at exports.index (D:\SwitchJS\citydiSwicthNodeV1\controllers\index.js:20:16)
    at Layer.handle [as handle_request] (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\layer.js:95:5)
    at D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\index.js:335:12)
    at next (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\index.js:275:10)

it is my code

MyPackager.js File
var jspos = require("jspos") 

let { IFB_NUMERIC, IFB_BITMAP, IFB_LLNUM, IFB_LLLNUM, IF_CHAR, IFB_LLCHAR, IFB_LLLCHAR, IFB_BINARY, IFB_LLBINARY, IFB_LLLBINARY, IFB_AMOUNT } = jspos.packer;
const pad = false;
let fld = [
    /*000*/ new IFB_NUMERIC(4, "Message Type Indicator", true),
    /*001*/ new IFB_BITMAP(8, "Bitmap"),
    /*002*/ new IFB_LLNUM(19, "Primary Account number", pad),
    /*003*/ new IFB_NUMERIC(6, "Processing Code", pad),
    /*004*/ new IFB_NUMERIC(12, "Amount, Transaction", pad),
    /*005*/ new IFB_NUMERIC(12, "Amount, Reconciliation", pad),
    /*006*/ new IFB_NUMERIC(12, "Amount, Cardholder billing", pad),
    /*007*/ new IFB_NUMERIC(10, "Date and time, transmission", pad),
    /*008*/ new IFB_NUMERIC(8, "Amount, Cardholder billing fee", pad)
];

class MyPackager extends jspos.ISOBasePackager{
     constructor() {
        super();
          this.setFieldPackager(fld);
     }
}
exports.GetPakager= new MyPackager();

----------------------------------------------------------
controllers/index.js File

exports.index = function (req, res, next) {

  try { 
    console.log('dddd');
    debugger;
    var jspos = require("jspos");
    var packager = require("./MyPackager");
    var msg = packager.GetPakager.createISOMsg();

    msg.setMTI('0800');
    msg.setField(11, '000105');
    msg.setField(41, '00000764');
    msg.setField(42, '111000001111002');
    msg.setField(60, '00000001003');
    msg.setField(63, '001');
    var tt=msg.pack();
    console.log(jspos.ISOUtil.hexString(msg.pack()));

    let msgStr = '08000020000000C00012000105303030303037363431313130303030303131313130303200110000000100300003303031';
     let unpackMsg = packager.GetPakager.createISOMsg();
     unpackMsg.unpack(jspos.ISOUtil.hex2byte(msgStr));
     console.log(jspos.ISOUtil.hexString(unpackMsg.pack()));
    res.render('index', { title: 'wwwww' });

  }
  catch (exceptiopn) {
    console.log(exceptiopn)
    logger2.error(exceptiopn);
  }

};

------------------------------------------------------
plese helpe me and tell me my problem

thanks

**Comment by makexxoo** [comment]
let fld = [
/000/ new IFB_NUMERIC(4, "Message Type Indicator", true),
/001/ new IFB_BITMAP(8, "Bitmap"),
/002/ new IFB_LLNUM(19, "Primary Account number", pad),
/003/ new IFB_NUMERIC(6, "Processing Code", pad),
/004/ new IFB_NUMERIC(12, "Amount, Transaction", pad),
/005/ new IFB_NUMERIC(12, "Amount, Reconciliation", pad),
/006/ new IFB_NUMERIC(12, "Amount, Cardholder billing", pad),
/007/ new IFB_NUMERIC(10, "Date and time, transmission", pad),
/008/ new IFB_NUMERIC(8, "Amount, Cardholder billing fee", pad)，
...
/011/ new IFB_NUMERIC(8, "Amount, Cardholder billing fee", pad)
];

you need define field 11
________________________________
发件人: mehrshadghaderian <notifications@github.com>
发送时间: 2019年6月6日 7:18
收件人: sitb-software/jsPOS
抄送: Subscribed
主题: [sitb-software/jsPOS] Nodejs Express and jspos (#17)


please help me

i use jpos in .net project in enterprise Project . but now when i see npm-jspos i realy happy .

i use from your example
but becase of i dont have typescript file in express frame work i change code but i have error in 'msg.pack()'

Error: null field 11 packager
at MyPackager.pack (D:\SwitchJS\citydiSwicthNodeV1\node_modules\jspos\lib\ISOBasePackager.js:144:31)
at ISOMsg.pack (D:\SwitchJS\citydiSwicthNodeV1\node_modules\jspos\lib\ISOMsg.js:180:34)
at exports.index (D:\SwitchJS\citydiSwicthNodeV1\controllers\index.js:20:16)
at Layer.handle [as handle_request] (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\layer.js:95:5)
at next (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\route.js:137:13)
at Route.dispatch (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\route.js:112:3)
at Layer.handle [as handle_request] (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\layer.js:95:5)
at D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\index.js:281:22
at Function.process_params (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\index.js:335:12)
at next (D:\SwitchJS\citydiSwicthNodeV1\node_modules\express\lib\router\index.js:275:10)

it is my code

MyPackager.js File
var jspos = require("jspos")

let { IFB_NUMERIC, IFB_BITMAP, IFB_LLNUM, IFB_LLLNUM, IF_CHAR, IFB_LLCHAR, IFB_LLLCHAR, IFB_BINARY, IFB_LLBINARY, IFB_LLLBINARY, IFB_AMOUNT } = jspos.packer;
const pad = false;
let fld = [
/000/ new IFB_NUMERIC(4, "Message Type Indicator", true),
/001/ new IFB_BITMAP(8, "Bitmap"),
/002/ new IFB_LLNUM(19, "Primary Account number", pad),
/003/ new IFB_NUMERIC(6, "Processing Code", pad),
/004/ new IFB_NUMERIC(12, "Amount, Transaction", pad),
/005/ new IFB_NUMERIC(12, "Amount, Reconciliation", pad),
/006/ new IFB_NUMERIC(12, "Amount, Cardholder billing", pad),
/007/ new IFB_NUMERIC(10, "Date and time, transmission", pad),
/008/ new IFB_NUMERIC(8, "Amount, Cardholder billing fee", pad)
];

class MyPackager extends jspos.ISOBasePackager{
constructor() {
super();
this.setFieldPackager(fld);
}
}
exports.GetPakager= new MyPackager();

________________________________

controllers/index.js File

exports.index = function (req, res, next) {

try {
console.log('dddd');
debugger;
var jspos = require("jspos");
var packager = require("./MyPackager");
var msg = packager.GetPakager.createISOMsg();

msg.setMTI('0800');
msg.setField(11, '000105');
msg.setField(41, '00000764');
msg.setField(42, '111000001111002');
msg.setField(60, '00000001003');
msg.setField(63, '001');
var tt=msg.pack();
console.log(jspos.ISOUtil.hexString(msg.pack()));

let msgStr = '08000020000000C00012000105303030303037363431313130303030303131313130303200110000000100300003303031';
 let unpackMsg = packager.GetPakager.createISOMsg();
 unpackMsg.unpack(jspos.ISOUtil.hex2byte(msgStr));
 console.log(jspos.ISOUtil.hexString(unpackMsg.pack()));
res.render('index', { title: 'wwwww' });


}
catch (exceptiopn) {
console.log(exceptiopn)
logger2.error(exceptiopn);
}

};

________________________________

plese helpe me and tell me my problem

thanks

―
